---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-editor

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-editor-nonroot
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - nonroot

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-editor-nonroot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-editor-nonroot
subjects:
  - kind: ServiceAccount
    name: default-editor
